[tool.poetry]
name = "kol-torah-db"
version = "0.1.0"
description = "Database package with SQLAlchemy models and migrations for Kol Torah"
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "kol_torah_db"}]

[tool.poetry.dependencies]
python = "^3.9"
sqlalchemy = "^2.0.0"
psycopg2-binary = "^2.9.0"
alembic = "^1.13.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
black = "^23.0.0"
flake8 = "^6.1.0"
mypy = "^1.7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
